### ISSUE TITLE
White list email addresses, domains, etc

### ISSUE THREAD

**Issue by pupeno** [uw-it-aca/django-saferecipient-email-backend#7]
Is it possible to white list email addresses and domains? For example, I work at Acme Inc, so, I want emails to @acmeinc.com to be delivered to the correct address, but all other emails to be delivered to test@acmeinc.com. This is a feature I loved at https://github.com/stemps/mailsafe

If this is not possible, would you be interested in a PR? are you actively maintaining this library?

**Comment by jlaney** [comment]
Added, this will be released as v1.1.

**Comment by pupeno** [comment]
I made some improvements to this in a private copy. I'll try to have the
pull request ready today.
